name: plinkskat
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.2.0
  - r-skat=2.2.4
  - r-metaskat=0.82
  - r-argparser=0.7.1
  - r-dplyr=1.0.10
  - r-data.table=1.14.4
  - r-ggplot2=3.3.6
  - r-ggrepel=0.9.1
  - r-ggbeeswarm=0.6.0
  - r-scales=1.2.1
  - r-qqman=0.1.8
  - r-rmeta=3.0

